# -*- coding: utf-8 -*-
"""unit4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19F6dBFvGikcW8NVpvrLoJYuKbcAuh9pm
"""

# Install dependencies (if needed)
!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample dataset
texts = ["I love this movie", "This film is terrible", "Amazing experience", "Worst acting ever"]
labels = [1, 0, 1, 0]

# Tokenization
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

X = pad_sequences(sequences, maxlen=10)
y = tf.constant(labels)

# Model
model = Sequential([
    Embedding(input_dim=1000, output_dim=64, input_length=10),
    SimpleRNN(64),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=5)

# Prediction
print(model.predict(X))

from tensorflow.keras.layers import LSTM

model = Sequential([
    Embedding(input_dim=1000, output_dim=64, input_length=10),
    LSTM(64),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=5)

print(model.predict(X))

!pip install transformers datasets torch

from transformers import BertTokenizer, BertForSequenceClassification
import torch

# Load tokenizer & model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

# Sample input
texts = ["I love this product", "This is the worst thing ever"]
labels = torch.tensor([1, 0])

# Tokenize
inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")

# Forward pass
outputs = model(**inputs, labels=labels)

loss = outputs.loss
logits = outputs.logits

print("Loss:", loss.item())
print("Logits:", logits)

from transformers import RobertaTokenizer, RobertaForSequenceClassification

# Load tokenizer & model
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaForSequenceClassification.from_pretrained('roberta-base')

# Sample input
texts = ["I really enjoyed this!", "It was a horrible experience"]
labels = torch.tensor([1, 0])

# Tokenize
inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")

# Forward pass
outputs = model(**inputs, labels=labels)

loss = outputs.loss
logits = outputs.logits

print("Loss:", loss.item())
print("Logits:", logits)